[2024-05-14T07:47:15.336+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-14T07:47:15.345+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_jobs104.data_lake manual__2024-05-14T07:47:07.753695+00:00 [queued]>
[2024-05-14T07:47:15.349+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_jobs104.data_lake manual__2024-05-14T07:47:07.753695+00:00 [queued]>
[2024-05-14T07:47:15.349+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-14T07:47:15.354+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_lake> on 2024-05-14 07:47:07.753695+00:00
[2024-05-14T07:47:15.358+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=583) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-14T07:47:15.358+0000] {standard_task_runner.py:63} INFO - Started process 585 to run task
[2024-05-14T07:47:15.359+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_jobs104', 'data_lake', 'manual__2024-05-14T07:47:07.753695+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_jobs104.py', '--cfg-path', '/tmp/tmp7cvcb9i5']
[2024-05-14T07:47:15.360+0000] {standard_task_runner.py:91} INFO - Job 56: Subtask data_lake
[2024-05-14T07:47:15.384+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline_jobs104.data_lake manual__2024-05-14T07:47:07.753695+00:00 [running]> on host 9bf348f884a5
[2024-05-14T07:47:15.424+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline_jobs104' AIRFLOW_CTX_TASK_ID='data_lake' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T07:47:07.753695+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-14T07:47:07.753695+00:00'
[2024-05-14T07:47:15.425+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-14T07:47:15.431+0000] {logging_mixin.py:188} INFO - data_lake !!!
[2024-05-14T07:47:15.431+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-14T07:47:15.431+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-14T07:47:15.435+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_pipeline_jobs104, task_id=data_lake, run_id=manual__2024-05-14T07:47:07.753695+00:00, execution_date=20240514T074707, start_date=20240514T074715, end_date=20240514T074715
[2024-05-14T07:47:15.460+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-14T07:47:15.469+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-14T07:47:15.470+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
